# Generated by Django 3.2.6 on 2021-08-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210817_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'google')], max_length=20)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_medias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Social Media',
            },
        ),
    ]
