# Generated by Django 3.2.6 on 2021-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='category',
            field=models.CharField(choices=[('respiratory', 'Respiratory'), ('oxygen', 'Oxygen'), ('heart_rate', 'Heart Rate'), ('temperature', 'Temperature'), ('viscosity', 'Viscosity')], max_length=50),
        ),
    ]
