# Generated by Django 3.2.6 on 2021-08-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backapi', '0002_alter_measurement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
