# Generated by Django 3.2.6 on 2021-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0003_auto_20210821_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductCreditSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('-created',)},
        ),
    ]
